apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      restartPolicy: "Always"
      containers:
        - name: redis-pod
          image: redis:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: 800Mi
              cpu: "0.25"
            limits:
              memory: 2Gi
              cpu: "0.5"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    io.kompose.service: redis
spec:
  ports:
    - name: "6389"
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    io.kompose.service: redis
